### ISSUE TITLE
libukui-log4qt.so.1 依赖

### ISSUE THREAD

**Issue by sonichy** [UbuntuKylin/kylin-ipmsg#14]
error while loading shared libraries: libukui-log4qt.so.1: cannot open shared object file: No such file or directory
希望减少依赖，以便在非UKUI系统使用。

**Comment by hyh19962008** [comment]
自己编译可以去掉这个依赖，少了日志记录功能，不影响使用。
main.cpp： 注释掉"#include <ukui-log4qt.h>" 以及 iniUkuiLog4qt("kylin-ipmsg")
kyin-ipmsg.pro: 删掉 -lukui-log4qt
